version: '3.3'

services:

  emulator:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: yoi/emulator:v1
    restart: always
    container_name: yoi-emulator
    hostname: yoi-emulator
    networks:
      yoinet:
        aliases:
          - yoi-emulator

networks:
  yoinet:
    driver: 'bridge'
...
