version: '3.3'

services:

  emulator:
    build:
      context: ../
      dockerfile: ./Dockerfile
    image: pnoker/boot-project:v1
    restart: always
    container_name: boot-project
    hostname: boot-project
    networks:
      net:
        aliases:
          - boot-project

networks:
  net:
    driver: 'bridge'
...
